use_frameworks!

#platform :ios, '8.0'

target 'GHTimeProfiler_Example' do
  pod 'GHTimeProfiler/TimeProfiler', :path => '../'

  target 'GHTimeProfiler_Tests' do
    inherit! :search_paths

    
  end
end
